#! /bin/sh

bspc config top_padding		16		

bspc config border_width        1
bspc config window_gap         	4

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Iceweasel desktop=^2

panel &
